"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _landing_map_preview from './landing-map-preview.bones.json'

configureBoneyard({"color":"rgba(42, 45, 58, 0.86)","animate":"shimmer","shimmerColor":"rgba(208, 32, 32, 0.20)","transition":300})

registerBones({
  "landing-map-preview": _landing_map_preview,
})
